In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("C:\\Users\\Dell\\Downloads\\ecommerce_sales_data.csv")

In [5]:
df.head()

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

In [6]:
df.count

<bound method DataFrame.count of       Order Date Product Name     Category Region  Quantity  Sales   Profit
0     2024-12-31      Printer       Office  North         4   3640   348.93
1     2022-11-27        Mouse  Accessories   East         7   1197   106.53
2     2022-05-11       Tablet  Electronics  South         5   5865   502.73
3     2024-03-16        Mouse  Accessories  South         2    786   202.87
4     2022-09-10        Mouse  Accessories   West         1    509   103.28
...          ...          ...          ...    ...       ...    ...      ...
3495  2023-02-15      Monitor  Accessories  North         4   4064   771.16
3496  2022-09-18      Monitor  Accessories   East         1   1117   119.89
3497  2022-04-12       Laptop  Electronics  South         4    260    66.02
3498  2022-01-18      Printer       Office  South         3    222    50.28
3499  2024-11-01   Smartwatch  Electronics   East         9  10530  1777.32

[3500 rows x 7 columns]>

In [16]:
df.shape

(3500, 10)

In [7]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3500 non-null   object
 1   Product Name  3500 non-null   object
 2   Category      3500 non-null   object
 3   Region        3500 non-null   object
 4   Quantity      3500 non-null   int64
 5   Sales         3500 non-null   int64
 6   Profit        3500 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 191.5+ KB

In [23]:
df.describe

<bound method NDFrame.describe of      Order_Date Product_Name     Category Region  Quantity  Sales   Profit  \
0    2024-12-31      Printer       Office  North         4   3640   348.93
1    2022-11-27        Mouse  Accessories   East         7   1197   106.53
2    2022-05-11       Tablet  Electronics  South         5   5865   502.73
3    2024-03-16        Mouse  Accessories  South         2    786   202.87
4    2022-09-10        Mouse  Accessories   West         1    509   103.28
...         ...          ...          ...    ...       ...    ...      ...
3495 2023-02-15      Monitor  Accessories  North         4   4064   771.16
3496 2022-09-18      Monitor  Accessories   East         1   1117   119.89
3497 2022-04-12       Laptop  Electronics  South         4    260    66.02
3498 2022-01-18      Printer       Office  South         3    222    50.28
3499 2024-11-01   Smartwatch  Electronics   East         9  10530  1777.32

      Year  Month Month_Name
0     2024     12        Dec
1     2022     11        Nov
2     2022      5        May
3     2024      3        Mar
4     2022      9        Sep
...    ...    ...        ...
3495  2023      2        Feb
3496  2022      9        Sep
3497  2022      4        Apr
3498  2022      1        Jan
3499  2024     11        Nov

[3500 rows x 10 columns]>

In [8]:
df.columns=df.columns.str.strip().str.replace(" ","_")

In [22]:
df.columns

Index(['Order_Date', 'Product_Name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit', 'Year', 'Month', 'Month_Name'],
      dtype='object')

In [11]:
df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')

In [12]:
print(df['Order_Date'].head())

0   2024-12-31
1   2022-11-27
2   2022-05-11
3   2024-03-16
4   2022-09-10
Name: Order_Date, dtype: datetime64[ns]

In [20]:
df.isnull().sum()
#df.fillna(0)

Order_Date      0
Product_Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
Year            0
Month           0
Month_Name      0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.drop_duplicates()

     Order_Date Product_Name     Category Region  Quantity  Sales   Profit
0    2024-12-31      Printer       Office  North         4   3640   348.93
1    2022-11-27        Mouse  Accessories   East         7   1197   106.53
2    2022-05-11       Tablet  Electronics  South         5   5865   502.73
3    2024-03-16        Mouse  Accessories  South         2    786   202.87
4    2022-09-10        Mouse  Accessories   West         1    509   103.28
...         ...          ...          ...    ...       ...    ...      ...
3495 2023-02-15      Monitor  Accessories  North         4   4064   771.16
3496 2022-09-18      Monitor  Accessories   East         1   1117   119.89
3497 2022-04-12       Laptop  Electronics  South         4    260    66.02
3498 2022-01-18      Printer       Office  South         3    222    50.28
3499 2024-11-01   Smartwatch  Electronics   East         9  10530  1777.32

[3500 rows x 7 columns]

In [15]:
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month
df['Month_Name'] = df['Order_Date'].dt.strftime('%b')

In [26]:
df.to_csv('cleaned_sales_data.csv',index=False)